PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX RO: <http://purl.obolibrary.org/obo/RO_>

SELECT distinct ?graph, ?property, ?taxon, ?label

WHERE { 
  VALUES ?property {
    RO:0002162 # in taxon
    RO:0002160 # only in taxon
    RO:0002175 # present in taxon
  }
  GRAPH ?graph {
    ?s owl:onProperty ?property ;
       owl:someValuesFrom ?taxon .
    ?taxon rdfs:label ?label .
  }
}
